project: 
  type: website
  output-dir: docs # renders htmls to docs folder

website:
  title: "Data Warehousing Notebook"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/1Ramirez7/Portfolio_Template
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line
  

execute:
  freeze: false   # ⛔ disables auto-skip
  cache: false    # ⛔ disables .quarto or chunk caching

  page-footer: 
    border: true
    left: "Eduardo Ramirez 2025©"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/


  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "Week Introductions"
        file: intro.qmd


  sidebar:
    - title: "Week Introductions"
      style: "docked"
      background: light
      contents:
        - text: "Week Introductions"
          file: intro.qmd
        - text: "Project 1 name"
          file: intro/week1.qmd
        - text: "project 2 name"
          file: intro/week2.qmd
        - text: "project 3 name"
          file: intro/week3.qmd
        #continue the pattern if you need more links
        #copy paste from title and keep it indented to sidebar to add additonal sidebar navigation for other pages



format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: flatly # more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true
